# Generated by Django 3.1.7 on 2021-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_img/default.png', null=True, upload_to='profile_img'),
        ),
    ]
